# Generated by Django 5.2.4 on 2025-07-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
